"""
Phase 17 - FastAPI Deployment Layer
=====================================

Exposes the same document-processing pipeline app.py uses
(Phases 1-6, 9, 12, 13) as a REST API. This does NOT replace
app.py - it's an additional, independent interface built on the
same services/ modules, useful for programmatic/integration
access rather than the interactive Streamlit dashboard.

Run locally:
    uvicorn api:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

import hashlib
import os
import tempfile

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from src.extraction.pdf_processor import (
    extract_text_from_file,
    clean_text,
)
from src.extraction.document_classifier import classify_document
from src.processors.discharge_processor import extract_discharge_information
from src.processors.medicine_processor import extract_medicine_information
from src.processors.lab_processor import extract_lab_information
from src.processors.radiology_processor import extract_radiology_information
from src.processors.cardiology_processor import extract_cardiology_information
from src.nlp.summarizer import generate_summary
from src.nlp.rag_engine import index_document, answer_with_rag
from src.clinical.decision_support import analyze_decision_support
from src.nlp.translation_service import (
    translate_medical_text,
    translate_medical_document,
)
from src.reports.report_generator import generate_pdf_report
from src.search.search_service import (
    list_documents,
    delete_document as delete_from_library,
)
from src.storage.document_store import (
    save_document_result,
    load_document_result,
    delete_document_result,
)

app = FastAPI(
    title="Intelligent Healthcare Document Assistant API",
    description=(
        "REST API for medical document processing: extraction, "
        "summarization, decision support, translation, and "
        "downloadable reports. Educational/development use only - "
        "not a medical diagnosis tool."
    ),
    version="1.0.0",
)


UPLOAD_FOLDER = "uploads"
TEXT_FOLDER = "extracted_text"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(TEXT_FOLDER, exist_ok=True)

# Keep this in sync with app.py's st.file_uploader(type=[...]) list
# so both entry points accept exactly the same set of formats.
ALLOWED_EXTENSIONS = {".pdf", ".docx", ".jpg", ".jpeg", ".png"}


class AskRequest(BaseModel):
    question: str


class TranslateRequest(BaseModel):
    target_language: str


def _classify_and_extract(document_type: str, cleaned_text: str) -> dict:

    normalized_type = document_type.lower()

    if "discharge" in normalized_type or "summary" in normalized_type:
        return extract_discharge_information(cleaned_text)

    if "general" in normalized_type or "medicine" in normalized_type:
        return extract_medicine_information(cleaned_text)

    if "lab" in normalized_type or "laboratory" in normalized_type:
        return extract_lab_information(cleaned_text)

    if (
        "radiology" in normalized_type
        or "mri" in normalized_type
        or "ct" in normalized_type
    ):
        return extract_radiology_information(cleaned_text)

    if "cardiology" in normalized_type or "cardiac" in normalized_type:
        return extract_cardiology_information(cleaned_text)

    return {}


@app.get("/api/health")
def health_check():
    return {"status": "ok"}


@app.post("/api/documents/upload")
async def upload_document(file: UploadFile = File(...)):
    """
    Upload a medical document (PDF, DOCX, JPG, JPEG, or PNG) and run
    it through the full processing pipeline: text extraction (with
    OCR fallback for scanned PDFs and images) -> cleaning ->
    classification -> structured extraction -> summarization -> RAG
    indexing -> decision support (risks, drug interactions, referrals).
    """

    file_extension = os.path.splitext(file.filename)[1].lower()

    if file_extension not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            400,
            f"Unsupported file type: '{file_extension}'. "
            f"Supported types are: {', '.join(sorted(ALLOWED_EXTENSIONS))}",
        )

    file_bytes = await file.read()
    document_id = hashlib.md5(file_bytes).hexdigest()

    temp_path = os.path.join(UPLOAD_FOLDER, file.filename)
    with open(temp_path, "wb") as f:
        f.write(file_bytes)

    raw_text, extraction_method = extract_text_from_file(temp_path)

    if not raw_text or not raw_text.strip():
        raise HTTPException(422, "No text could be extracted from this document.")

    cleaned_text = clean_text(raw_text)

    document_type = classify_document(cleaned_text)

    structured_data = _classify_and_extract(document_type, cleaned_text)

    summary = generate_summary(structured_data, document_type) or ""

    index_document(
        document_text=cleaned_text,
        document_name=file.filename,
        document_type=document_type,
        document_id=document_id,
        clear_existing=True,
    )

    decision_result = analyze_decision_support(
        data=structured_data,
        document_type=document_type,
    )

    result = {
        "document_id": document_id,
        "document_name": file.filename,
        "document_type": document_type,
        "extraction_method": extraction_method,
        "structured_data": structured_data,
        "summary": summary,
        "overall_risk": decision_result.get("overall_risk", "Low"),
        "risks": decision_result.get("risks", []),
        "drug_interactions": decision_result.get("drug_interactions", []),
        "referrals": decision_result.get("referrals", []),
        "document_text": cleaned_text,
    }

    save_document_result(document_id, result)

    return result


@app.get("/api/documents")
def list_all_documents():
    """List every document indexed in the Phase 10 search library."""
    return list_documents()


@app.get("/api/documents/{document_id}")
def get_document(document_id: str):
    """Retrieve a previously processed document's full results."""
    result = load_document_result(document_id)
    if not result:
        raise HTTPException(404, "Document not found.")
    return result


@app.delete("/api/documents/{document_id}")
def delete_document_endpoint(document_id: str):
    """Remove a document from both the search library and local storage."""
    delete_from_library(document_id)
    deleted = delete_document_result(document_id)
    return {"success": True, "deleted_local_record": deleted}


@app.post("/api/documents/{document_id}/ask")
def ask_question(document_id: str, request: AskRequest):
    """Ask a question about a specific, already-processed document."""

    result = load_document_result(document_id)
    if not result:
        raise HTTPException(404, "Document not found.")

    answer = answer_with_rag(
        question=request.question,
        document_text=result["document_text"],
        top_k=5,
        document_id=document_id,
    )

    if isinstance(answer, dict):
        answer = answer.get("answer", str(answer))
    elif isinstance(answer, tuple):
        answer = answer[0]

    return {"question": request.question, "answer": str(answer)}


@app.post("/api/documents/{document_id}/translate")
def translate_document(document_id: str, request: TranslateRequest):
    """Translate a processed document's text into another language."""

    result = load_document_result(document_id)
    if not result:
        raise HTTPException(404, "Document not found.")

    try:
        translated = translate_medical_document(
            text=result["document_text"],
            target_language=request.target_language,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))

    return {
        "target_language": request.target_language,
        "translated_text": translated,
    }


@app.get("/api/documents/{document_id}/report")
def download_report(document_id: str):
    """Generate and return a downloadable PDF report for a document."""

    result = load_document_result(document_id)
    if not result:
        raise HTTPException(404, "Document not found.")

    report_path = os.path.join(
        tempfile.gettempdir(), f"medical_report_{document_id}.pdf"
    )

    generate_pdf_report(
        output_path=report_path,
        document_name=result.get("document_name"),
        document_type=result.get("document_type"),
        extraction_method=result.get("extraction_method"),
        summary=result.get("summary"),
        structured_data=result.get("structured_data"),
        risks=result.get("risks"),
        overall_risk=result.get("overall_risk", "Low"),
        drug_interactions=result.get("drug_interactions"),
        referrals=result.get("referrals"),
    )

    return FileResponse(
        report_path,
        media_type="application/pdf",
        filename=f"medical_report_{document_id}.pdf",
    )